#!/bin/bash
PERSON1=$1
PERSON2=$2

echo "$PERSON1:: wELCOME TO ALASKA $PERSON2"
echo "$PERSON2:: Thank you $PERSON1, fINALLY NOT ON ZOOM CALL"
echo "$PERSON1:: SO, DO WE HAVE A DEAL"
echo "$PERSON2:: YES, IF YOU MAKE UKRAINE JOINS RUSSIA"